services:
  - type: web
    name: pssssss
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
